### ISSUE TITLE
1.05 issues

### ISSUE THREAD

**Issue by johnsalow** [weather34/Meteobridge-MB-SMART#12]
Forecast summary shows in metric when set to imperial
Earthquake is showing mag 0.0 with no location even though eqnotification.txt has earthquakes
Davis console forecast summary blank if Meteobridge Pro. 
If use WU small forecast, displays in metric when set to imperial
If run updater, says successful but continues to list same update as needing to be applied 201910311015.zip

**Comment by weather34** [comment]
url ?

**Comment by johnsalow** [comment]
lakeforestweather.com, laventanaweather.com, clubcerralvo.com

Thx

**Comment by weather34** [comment]
ok 1st link goes to meteotemplate as it opens up in full menu on my ipad so that show this template 
2nd link ok so ill take a look at what needs fixing in the small forecast option please monitor the info page https//weather34.com/homeweatherstation for updates this repo will go back to private shortly next week i opened up for only one use who couldnt get links via info page.

3rd link returned nothing after two minutes here in istanbul

**Comment by johnsalow** [comment]
Try these

lakeforestweather.com/mbsmart
laventanaweather.com/mbsmart
clubcerralvoweather.com/mbsmart (had the 3rd link wrong domain sorry)

**Comment by weather34** [comment]
http://laventanaweather.com/mbsmart/ switch that to use small forecast so I can see if there is anything obvious as mine locally shows non metric when using imperial , remember it doesn't change metrics as it is human text it will only display what is setup in the setup screen 

**
*important set units for Weather Underground API     
e = Imperial(Non Metric) 
m = Metric 
s = m/s wind speed + metric(Scandinavia) 
h = mph wind speed + metric(UK)**

**Comment by johnsalow** [comment]
I removed the password for laventanaweather.com so you can mess with it. I think I have WU set to metric because when I changed it to imperial it screwed things up. But maybe that was an old version.

**Comment by weather34** [comment]
ok you had wu set to get metric I now changed it . please set your password again this is a public forum .should look ok now

**Comment by johnsalow** [comment]
thx. What about the earthquake not working?

**Comment by weather34** [comment]
are you using an older version of stationcron.php as the earthquake API provider was changed ? and your http://www.laventanaweather.com/mbsmart/jsondata/eqnotification.txt is reflecting the old API provider

**Comment by johnsalow** [comment]
Yes because the new one was creating empty forecasts. But I haven’t had a chance to try to other line you suggested a few days ago. Will give it a go. Thx

**Comment by weather34** [comment]
I haven't suggested anything I have been away until this afternoon. if your using older versions I can help much with issues as they are somewhat different. never mix anything with older released versions . please just upload the current stationcron.php and we will see if we can see what the issues are .

**Comment by johnsalow** [comment]
I put the 1.05 version of stationcron.php back in laventanaweather.com. it creates new files in jsondata with 0kb for metar34 and wuforecast

**Comment by weather34** [comment]
now unlock again password

**Comment by johnsalow** [comment]
Done

**Comment by weather34** [comment]
try attached stationcron 
[stationcron.php.zip](https://github.com/weather34/Meteobridge-MB-SMART/files/3800702/stationcron.php.zip)

**Comment by johnsalow** [comment]
Now all 3 text files are created as 0kb. Eqnotification was working in original 1.05 stationcron

**Comment by weather34** [comment]
which version of stationcron.php from previous were you using because I need to break this down one by one so the stationcron.php that worked for you delivering forecast can you upload it here so I can compare the difference

**Comment by weather34** [comment]
this may be a unique server config out of 124 users of version 1.05 I have not had this issue raised and just checked all through emails I don't see anything related as everyone is using the same file for forecast/earthquake etc. there are other minor issues but nothing preventing data display

**Comment by johnsalow** [comment]
[mbdbfiles.zip](https://github.com/weather34/Meteobridge-MB-SMART/files/3800711/mbdbfiles.zip)

**Comment by johnsalow** [comment]
its windows server 2019 IIS. the new stationcron is updating the files changing mod time but writes 0kb. old one works for some reason

**Comment by weather34** [comment]
ok try attached
[stationcron-old-works.php.zip](https://github.com/weather34/Meteobridge-MB-SMART/files/3800714/stationcron-old-works.php.zip)

**Comment by johnsalow** [comment]
perfect! thanks for all your help

**Comment by weather34** [comment]
ok now update attached a minor different issue raised today 
[windgustyear.php.zip](https://github.com/weather34/Meteobridge-MB-SMART/files/3800717/windgustyear.php.zip)

**Comment by weather34** [comment]
ok so lets fix another minor issue 

[windgustyear.php.zip](https://github.com/weather34/Meteobridge-MB-SMART/files/3800723/windgustyear.php.zip)

**Comment by johnsalow** [comment]
the file is -2 but I should remove that right? also check out the updater issue while I have the settings unlocked

**Comment by weather34** [comment]
I can't resolve server configurations no nothing about your server setup unfortunately these are things you will have to resolve , but file above just upload and replace existing.

**Comment by weather34** [comment]
ok job done I have to go now and im away for another week so apologies if don't get any response or replies ...Brian

**Comment by johnsalow** [comment]
I replaced it
![Screen Shot 2019-11-02 at 9 54 13 AM](https://user-images.githubusercontent.com/55805970/68074307-e0150700-fd56-11e9-81ac-3c0d371b3e37.png)

the updater lists two updates I've already applied and a new one for today. I don't really understand what its doing but maybe you can explain when you have more time. thx again

**Comment by weather34** [comment]
there backups you created hence the file name MB-SMART-BACKUP :-) just delete if you don't need them ..have a great weekend..Brian
