### ISSUE TITLE
alternative layout v2.0 in German?

### ISSUE THREAD

**Issue by johnsalow** [weather34/Meteobridge-MB-SMART#14]
switching to alternative layout is not using English labels

**Comment by weather34** [comment]
have you set the language to English = en in the alternative layout settings ? 

![Screenshot at Jan 02 00-35-04](https://user-images.githubusercontent.com/20555738/71646329-c2810100-2cf7-11ea-8794-0bb53689e044.png)

**Comment by johnsalow** [comment]
oh geez, didn't realize there were separate setting for that layout!
