### ISSUE TITLE
v 2.0 rocks but miss old bolder font

### ISSUE THREAD

**Issue by johnsalow** [weather34/Meteobridge-MB-SMART#15]
any plans to give font choice?

**Comment by weather34** [comment]
as it is im afraid again adding options needs some thought and Im not a lover of using google fonts or any cloud based options . but you can always edit the css files to use additional fonts .

@font-face { font-family: johnsalow; src: url(fonts/johnsalow.woff);}
@font-face { font-family: johnsalow; src: url(https://something/font/johnsalow.woff);}

then just place the **font-family: johnsalow;** in the css 
example 
body { font-family:johnsalow; }

**Comment by johnsalow** [comment]
thx. I changed weathertext2 and weathertext3 to src: url(fonts/HelveticaNeue-Medium.woff) format("woff"); and its way more readable imo.
