### ISSUE TITLE
feature request

### ISSUE THREAD

**Issue by johnsalow** [weather34/Meteobridge-MB-SMART#16]
would be nice to have the webcam module allow an additional webcam view. maybe a switch at top of module to select cam 1 or 2.

**Comment by weather34** [comment]
nice idea but needs some thought and more options to add to setup ..thanks

**Comment by alexeysailman** [comment]
Hello. There are several questions about Weather34 MB-SMART. I use the previous version for MB (for TP-LINK). In the settings, for the most part, everything remains the same. Recently installed MB-NanoSD. In the settings of Weather 34 MB-SMART did the same thing, but for some reason some things do not work, for example: 
- the wind speed is selected in m/s , but after saving it is still in km/h. 
- settings for WU are not working (weather not changing, although the WU website access statistics relevant), and even selecting units of measure "s" wind speed is still in km/h and the temperature is in Fahrenheit, but simbolos "C".

**Comment by weather34** [comment]
hello please provide a URL so I can take a look NANOSD works different from the TP-LINK types
we can take it from there.brian

**Comment by alexeysailman** [comment]
TP-LINK: https://xn--10-6kcwaznenhomt1p.xn--p1ai/
NANOSD: https://xn--10-6kcwaznenhomt1p.xn--p1ai/MBSMART/

**Comment by weather34** [comment]
check now you need to run the stationcron.php and other services via the NANOSD services tab.  Sorry but I see it is Russian?  thats not a part of the template im afraid so I would hold off changing translations until you are fully up and running otherwise it will be a bit confusing for me to help already I see the Russian language break the alignments . 

https://weather34.com/homeweatherstation/meteobridge-mb-smart-chartsetup.html

you also need to run stationcron.php at every 30 minutes or an hour

**Comment by alexeysailman** [comment]
Returned the original language pack for English. stationcron.php and other files are configured according to your instructions. By the way, the forecast from WU has earned, I will watch it. But the wind is still in km / h. And also pay attention to the third field on top: there is an inscription ([rain 0 total-max@M1]) in my opinion, it looks strange.

**Comment by weather34** [comment]
in your opinion yes but it actually means you have not added any history data for rainfall as your probably still in factory default mode no previous history data , when it rains it will have a record or you can add in december 2019 value if you have it . you will go through a learning curve so be a bit patient all will come good . good luck with russian and dont ask :-) for russian its a no but your free to do you own stuff to suit your needs .

**Comment by weather34** [comment]
wind is in ms here 
![A668987E-4B2E-4A7F-ACBC-ED669C80AA62](https://user-images.githubusercontent.com/20555738/72786683-3a7b8080-3c3f-11ea-9e97-d062b5435658.png)

**Comment by weather34** [comment]
as above your not running the stationcron.php every thirty minutes or hour if I run it through the browser it updates you also need to configure the language in the set up screen ..this oart works as you would have set up as per tp link.. topic is closed ..
