### ISSUE TITLE
Soucis css light 

### ISSUE THREAD

**Issue by neomanu16** [weather34/Meteobridge-MB-SMART#17]
Hi Brian,
there's a problem with the css light on iphone and ipad when you shoot it, it's no longer in the frame ...

![57628](https://user-images.githubusercontent.com/47469020/74084003-7baac780-4a6a-11ea-9ae4-3cc68d6a5c66.jpg)

**Comment by neomanu16** [comment]
> Salut Brian,
> il y a un problème avec la lumière css sur iphone et ipad lorsque vous le tirez, ce n'est plus dans le cadre ...
> 
> ![57628](https://user-images.githubusercontent.com/47469020/74084003-7baac780-4a6a-11ea-9ae4-3cc68d6a5c66.jpg)

The black ccs is also a concern

**Comment by weather34** [comment]
fix applied ... just now...many thanks

**Comment by neomanu16** [comment]
Brian,
I was wondering how did you achieve this?
![FireShot Capture 091 - Weather34 Stand Alone Weather Station for Sinanoba Istanbul - weather34 com](https://user-images.githubusercontent.com/47469020/74103290-4924cb80-4b4b-11ea-9741-8287a235b71b.png)
