### ISSUE TITLE
Luftdaten api endpoint changed

### ISSUE THREAD

**Issue by ettanin** [weather34/Meteobridge-MB-SMART#18]
My requests to get the luftdaten values are failing because the API endpoint has moved from 
https://api.luftdaten.info/v1/sensor/<id> to
https://data.sensor.community/airrohr/v1/sensor/<id>

**Comment by weather34** [comment]
Thanks I do not use luftdaten please find updated file attached (stationcron.zip)  unzip and replace stationcron.php in mbdbfiles folder …

Brian


Meteobridge MB-SMART weather template
https://weather34.com/homeweatherstation
