### ISSUE TITLE
Soucis ccs black

### ISSUE THREAD

**Issue by neomanu16** [weather34/Meteobridge-MB-SMART#19]
Hi Brian a little problem since the update,
![FireShot Capture 092 - Météo_Vars - www meteo16-vars com](https://user-images.githubusercontent.com/47469020/74595398-1134f100-5041-11ea-870f-65a56ce5f29d.png)

Best regard,
Emmanuel

**Comment by weather34** [comment]
See last push just now update two css files


Meteobridge MB-SMART weather template
https://weather34.com/homeweatherstation

**Comment by neomanu16** [comment]
I just tried it's the same nothing to change

**Comment by weather34** [comment]
Browser ? Url ? Would help


Meteobridge MB-SMART weather template
https://weather34.com/homeweatherstation

**Comment by neomanu16** [comment]
chrome 
http://www.meteo16-vars.com/console/consoledavis.php

**Comment by weather34** [comment]
Using latest pushed update for css files this I what I see in chrome I don’t see the same as you




Meteobridge MB-SMART weather template
https://weather34.com/homeweatherstation

**Comment by neomanu16** [comment]
the worry is out of place
![FireShot Capture 093 - Météo_Vars - www meteo16-vars com](https://user-images.githubusercontent.com/47469020/74595660-9a99f280-5044-11ea-8ddd-bdd4d04fd522.png)

**Comment by weather34** [comment]
![FR](https://user-images.githubusercontent.com/20555738/74595664-6f6bcf00-5055-11ea-9a11-0a3f0049fb75.png)

**Comment by neomanu16** [comment]
weird is that the black ccs

**Comment by weather34** [comment]
Did you update the indoor file see screenshot above it does not have a human icon it should show house icon


Meteobridge MB-SMART weather template
https://weather34.com/homeweatherstation

**Comment by weather34** [comment]
did you update the files  for  indoor and css because I can't see the same issue as you with chrome browser

**Comment by neomanu16** [comment]
Yes i did but nothing helped i don't understand

**Comment by weather34** [comment]
too me it is looking like the indoor file was not updated please check again

**Comment by weather34** [comment]
this file https://github.com/weather34/Meteobridge-MB-SMART/blob/master/console/indoortempmod.php

**Comment by weather34** [comment]
http://www.meteo16-vars.com/console/**indoortempmod.php**  is not the updated version ..

you need to update indoortempmod.php

**Comment by weather34** [comment]
it is very late here now just download and upload the file  indoortempmod.php  ...

**Comment by weather34** [comment]
voila have a good night ..Brian
