### ISSUE TITLE
 functionality request

### ISSUE THREAD

**Issue by neomanu16** [weather34/Meteobridge-MB-SMART#20]
Brian do you think it would be possible to make a webcam module
in the alternative version it would be perfect I could
replace the indoor.temp module

**Comment by weather34** [comment]
sure it will need an extra option look out for it next week sometime..

**Comment by neomanu16** [comment]
Thank you Brian it's cool I have a good job you do ....

**Comment by weather34** [comment]
have added option to show webcam 

requires css files to be updated and uploaded , upload updated console-setup.php , upload new weather-webcam.php file and make sure you update the settings screen with webcam url if option used .

![06A4F146-0711-4CE6-96A7-2B31A915EA53](https://user-images.githubusercontent.com/20555738/74601397-04e77d00-50af-11ea-8dc3-883b93a82011.png)

**Comment by neomanu16** [comment]
Thank you Brian I'll take care of s during the day ...

**Comment by weather34** [comment]
no problem ...

also has a webcam icon to enlarge in a pop up window..

![Screenshot_2020-02-16 Demo Home Weather Station(1)](https://user-images.githubusercontent.com/20555738/74601920-4c243c80-50b4-11ea-8a18-4531d5dd2dcd.png)

**Comment by neomanu16** [comment]
Weird at the moment it does not appear however I have to modify the console-setting.php file
I have half her ...
need to change elsewhere?
$uvsensor    = "weather34-webcam";

**Comment by neomanu16** [comment]
my image code is this and I can't get it integrated.

 <img src="http://g0.ipcamlive.com/player/snapshot.php?alias=5c699ebcc8710" alt="weathercam" class="webcamlarge">

**Comment by weather34** [comment]
just use the setup screen no need to edit files ..

**Comment by weather34** [comment]
like this 

![Screenshot_2020-02-16 Demo Home Weather Station](https://user-images.githubusercontent.com/20555738/74602801-bc838b80-50bd-11ea-8dfa-87d9cbab923d.png)

in the setup screen add the url

![Screenshot_2020-02-16 Screenshot](https://user-images.githubusercontent.com/20555738/74602803-c0afa900-50bd-11ea-9210-8eabcbddd22d.png)

**Comment by neomanu16** [comment]
I think it's good I have to update the last file and it must be good thank you Brian

**Comment by weather34** [comment]
this is what I see on your site , you need to update the files to reflect the larger pop up screen .. 5 files listed to be updated 

![Screenshot at Feb 16 13-17-09](https://user-images.githubusercontent.com/20555738/74602908-b0e49480-50be-11ea-911b-e07fff14db79.png)


![Screenshot_2020-02-16 Météo_Vars](https://user-images.githubusercontent.com/20555738/74602883-682cdb80-50be-11ea-8d59-a7955c9fad6b.png)

**Comment by neomanu16** [comment]
Thank you Brian all is ok now really thank you very much I would be lost without you ...

**Comment by weather34** [comment]
one more you need to get windmod.php it has translation for wind description .. have a good day..

**Comment by neomanu16** [comment]
Ok good sunday
