### ISSUE TITLE
Gros BUG

### ISSUE THREAD

**Issue by neomanu16** [weather34/Meteobridge-MB-SMART#21]
Hi Brian 

here is that it makes me, at times and if I in white I go to black and the problem is solved
and a few hours after his return ...
I don't see where it comes from at all .....
![FireShot Capture 094 - Météo_Vars - www meteo16-vars com](https://user-images.githubusercontent.com/47469020/74676267-e91ace80-51b5-11ea-94c4-69311c9d434a.png)

http://www.meteo16-vars.com/console/consoledavis.php

**Comment by weather34** [comment]
not loading css ... server limitation ? browser cache ? server cache ?  dont know not seen this before so cant help ...

**Comment by neomanu16** [comment]
I think I found yesterday when I made the configuration in the configuration that I made in French so I should have done in English it should have worked now ...
